/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LogoDownloadtip {
        /**
          * @default 'Download logo?'
         */
        "header": string;
        /**
          * @default []
         */
        "images": {
    link: string
    title: string
  }[];
        /**
          * @default 'right'
         */
        "position": 'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end';
        /**
          * @default 'light'
         */
        "theme": 'dark' | 'light';
    }
}
declare global {
    interface HTMLLogoDownloadtipElement extends Components.LogoDownloadtip, HTMLStencilElement {
    }
    var HTMLLogoDownloadtipElement: {
        prototype: HTMLLogoDownloadtipElement;
        new (): HTMLLogoDownloadtipElement;
    };
    interface HTMLElementTagNameMap {
        "logo-downloadtip": HTMLLogoDownloadtipElement;
    }
}
declare namespace LocalJSX {
    interface LogoDownloadtip {
        /**
          * @default 'Download logo?'
         */
        "header"?: string;
        /**
          * @default []
         */
        "images"?: {
    link: string
    title: string
  }[];
        /**
          * @default 'right'
         */
        "position"?: 'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end';
        /**
          * @default 'light'
         */
        "theme"?: 'dark' | 'light';
    }
    interface IntrinsicElements {
        "logo-downloadtip": LogoDownloadtip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "logo-downloadtip": LocalJSX.LogoDownloadtip & JSXBase.HTMLAttributes<HTMLLogoDownloadtipElement>;
        }
    }
}
